let a = {
  '!ref': 'A1:S11',
  A1: { t: 's', v: '序号', r: '<t>åºå·</t>', h: '序号', w: '序号' },
  B1: { t: 's', v: '工号', r: '<t>å·¥å·</t>', h: '工号', w: '工号' },
  C1: { t: 's', v: '姓名', r: '<t>å§å</t>', h: '姓名', w: '姓名' },
  D1: { t: 's', v: '本休参照日', r: '<t>æ¬ä¼åç§æ¥</t>', h: '本休参照日', w: '本休参照日' },
  E1: { t: 's', v: '不休参照日', r: '<t>ä¸ä¼åç§æ¥</t>', h: '不休参照日', w: '不休参照日' },
  F1: { t: 's', v: '日工作小时数', r: '<t>æ¥å·¥ä½å°æ¶æ°</t>', h: '日工作小时数', w: '日工作小时数' },
  G1: { t: 's', v: '排休天数', r: '<t>æä¼å¤©æ°</t>', h: '排休天数', w: '排休天数' },
  H1: { t: 'n', v: '' },
  I1: { t: 's', v: '日', r: '<t>æ¥</t>', h: '日', w: '日' },
  J1: { t: 's', v: '一', r: '<t>ä</t>', h: '一', w: '一' },
  K1: { t: 's', v: '二', r: '<t>äº</t>', h: '二', w: '二' },
  L1: { t: 's', v: '三', r: '<t>ä¸</t>', h: '三', w: '三' },
  M1: { t: 's', v: '四', r: '<t>å>', h: '四', w: '四' },
  N1: { t: 's', v: '五', r: '<t>äº</t>', h: '五', w: '五' },
  O1: { t: 's', v: '六', r: '<t>å</t>', h: '六', w: '六' },
  P1: { t: 's', v: '日', r: '<t>æ¥</t>', h: '日', w: '日' },
  Q1: { t: 's', v: '工时小计（h）', r: '<t>å·¥æ¶å°è®¡ï¼hï¼</t>', h: '工时小计（h）', w: '工时小计（h）' },
  R1: { t: 's', v: '备注', r: '<t>å¤æ³¨</t>', h: '备注', w: '备注' },
  S1: { t: 's', v: '员工签字', r: '<t>å·¥ç­¾å­</t>', h: '员工签字', w: '员工签字' },
  A2: { t: 'n', v: '' },
  B2: { t: 'n', v: '' },
  C2: { t: 'n', v: '' },
  D2: { t: 'n', v: '' },
  E2: { t: 'n', v: '' },
  F2: { t: 'n', v: '' },
  G2: { t: 'n', v: '' },
  H2: { t: 'n', v: '' },
  I2: { t: 'n', v: 1, w: '1' },
  J2: { t: 'n', v: 2, w: '2' },
  K2: { t: 'n', v: 3, w: '3' },
  L2: { t: 'n', v: 4, w: '4' },
  M2: { t: 'n', v: 5, w: '5' },
  N2: { t: 'n', v: 6, w: '6' },
  O2: { t: 'n', v: 7, w: '7' },
  P2: { t: 'n', v: 8, w: '8' },
  Q2: { t: 'n', v: '' },
  R2: { t: 'n', v: '' },
  S2: { t: 'n', v: '' },
  A3: { t: 'n', v: 1, w: '1' },
  B3: { t: 'n', v: 9940046, w: '9940046' },
  C3: { t: 's', v: '王志军', r: '<t>çå¿å>', h: '王志军', w: '王志军' },
  D3: { t: 's', v: '四', r: '<t>å>', h: '四', w: '四' },
  E3: { t: 's', v: '/', r: '<t>/</t>', h: '/', w: '/' },
  F3: { t: 'n', v: 8, w: '8' },
  G3: { t: 'n', v: 4, w: '4' },
  H3: { t: 's', v: '排班', r: '<t>æç­</t>', h: '排班', w: '排班' },
  I3: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  J3: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  K3: { t: 's', v: '休', r: '<t>ä¼</t>', h: '休', w: '休' },
  L3: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  M3: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  N3: { t: 's', v: '班', r: '<t>ç</t>', h: '班', w: '班' },
  O3: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  P3: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  Q3: { t: 'n', v: 200, w: '200' },
  R3: { t: 'n', v: '' },
  S3: { t: 'n', v: '' },
  A4: { t: 'n', v: '' },
  B4: { t: 'n', v: '' },
  C4: { t: 'n', v: '' },
  D4: { t: 'n', v: '' },
  E4: { t: 'n', v: '' },
  F4: { t: 'n', v: '' },
  G4: { t: 'n', v: '' },
  H4: { t: 's', v: '实际出勤', r: '<t>å®åºå¤</t>', h: '实际出勤', w: '实际出勤' },
  I4: { t: 'n', v: 8, w: '8' },
  J4: { t: 'n', v: 8, w: '8' },
  K4: { t: 'n', v: 8, w: '8' },
  L4: { t: 'n', v: 8, w: '8' },
  M4: { t: 'n', v: 8, w: '8' },
  N4: { t: 'n', v: 8, w: '8' },
  O4: { t: 'n', v: 8, w: '8' },
  P4: { t: 'n', v: 8, w: '8' },
  Q4: { t: 'n', v: '' },
  R4: { t: 'n', v: '' },
  S4: { t: 'n', v: '' },
  A5: { t: 'n', v: '' },
  B5: { t: 'n', v: '' },
  C5: { t: 'n', v: '' },
  D5: { t: 'n', v: '' },
  E5: { t: 'n', v: '' },
  F5: { t: 'n', v: '' },
  G5: { t: 'n', v: '' },
  H5: { t: 's', v: '加班小时数', r: '<t>å ç­å°æ¶æ°</t>', h: '加班小时数', w: '加班小时数' },
  I5: { t: 'n', v: '' },
  J5: { t: 'n', v: '' },
  K5: { t: 'n', v: '' },
  L5: { t: 'n', v: '' },
  M5: { t: 'n', v: '' },
  N5: { t: 'n', v: '' },
  O5: { t: 'n', v: '' },
  P5: { t: 'n', v: '' },
  Q5: { t: 'n', v: '' },
  R5: { t: 'n', v: '' },
  S5: { t: 'n', v: '' },
  A6: { t: 'n', v: 2, w: '2' },
  B6: { t: 'n', v: 9940078, w: '9940078' },
  C6: { t: 's', v: '王玲', r: '<t>çç²</t>', h: '王玲', w: '王玲' },
  D6: { t: 's', v: '三', r: '<t>ä¸</t>', h: '三', w: '三' },
  E6: { t: 's', v: '/', r: '<t>/</t>', h: '/', w: '/' },
  F6: { t: 'n', v: 8, w: '8' },
  G6: { t: 'n', v: 4, w: '4' },
  H6: { t: 's', v: '排班', r: '<t>æç­</t>', h: '排班', w: '排班' },
  I6: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  J6: { t: 's', v: '班', r: '<t>ç</t>', h: '班', w: '班' },
  K6: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  L6: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  M6: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  N6: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  O6: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  P6: { t: 's', v: '班', r: '<t>ç­</t>', h: '班', w: '班' },
  Q6: { t: 'n', v: 200, w: '200' },
  R6: { t: 'n', v: '' },
  S6: { t: 'n', v: '' },
  A7: { t: 'n', v: '' },
  B7: { t: 'n', v: '' },
  C7: { t: 'n', v: '' },
  D7: { t: 'n', v: '' },
  E7: { t: 'n', v: '' },
  F7: { t: 'n', v: '' },
  G7: { t: 'n', v: '' },
  H7: { t: 's', v: '实际出勤', r: '<t>å®åºå¤</t>', h: '实际出勤', w: '实际出勤' },
  I7: { t: 'n', v: 8, w: '8' },
  J7: { t: 'n', v: 8, w: '8' },
  K7: { t: 'n', v: 8, w: '8' },
  L7: { t: 'n', v: 8, w: '8' },
  M7: { t: 'n', v: 8, w: '8' },
  N7: { t: 'n', v: 8, w: '8' },
  O7: { t: 'n', v: 8, w: '8' },
  P7: { t: 'n', v: 8, w: '8' },
  Q7: { t: 'n', v: '' },
  R7: { t: 'n', v: '' },
  S7: { t: 'n', v: '' },
  A8: { t: 'n', v: '' },
  B8: { t: 'n', v: '' },
  C8: { t: 'n', v: '' },
  D8: { t: 'n', v: '' },
  E8: { t: 'n', v: '' },
  F8: { t: 'n', v: '' },
  G8: { t: 'n', v: '' },
  H8: { t: 's', v: '加班小时数', r: '<t>å ç­å°æ¶æ°</t>', h: '加班小时数', w: '加班小时数' },
  I8: { t: 'n', v: '' },
  J8: { t: 'n', v: '' },
  K8: { t: 'n', v: '' },
  L8: { t: 'n', v: '' },
  M8: { t: 'n', v: '' },
  N8: { t: 'n', v: '' },
  O8: { t: 'n', v: '' },
  P8: { t: 'n', v: '' },
  Q8: { t: 'n', v: '' },
  R8: { t: 'n', v: '' },
  S8: { t: 'n', v: '' },
  A9: { t: 'n', v: 3, w: '3' },
  B9: { t: 's', v: '当天在职人数', r: '<t>å½å¤©å¨èäººæ°</t>', h: '当天在职人数', w: '当天在职人数' },
  C9: { t: 'n', v: '' },
  D9: { t: 'n', v: '' },
  E9: { t: 'n', v: '' },
  F9: { t: 'n', v: '' },
  G9: { t: 'n', v: '' },
  H9: { t: 'n', v: '' },
  I9: { t: 'n', v: 2, w: '2' },
  J9: { t: 'n', v: 2, w: '2' },
  K9: { t: 'n', v: 2, w: '2' },
  L9: { t: 'n', v: 2, w: '2' },
  M9: { t: 'n', v: 2, w: '2' },
  N9: { t: 'n', v: 2, w: '2' },
  O9: { t: 'n', v: 2, w: '2' },
  P9: { t: 'n', v: 2, w: '2' },
  Q9: { t: 'n', v: '' },
  R9: { t: 'n', v: '' },
  S9: { t: 'n', v: '' },
  A10: { t: 'n', v: 4, w: '4' },
  B10: { t: 's', v: '缺编扣款', r: '<t>ç¼ºç¼æ£æ¬¾</t>', h: '缺编扣款', w: '缺编扣款' },
  C10: { t: 'n', v: '' },
  D10: { t: 'n', v: '' },
  E10: { t: 'n', v: '' },
  F10: { t: 'n', v: '' },
  G10: { t: 'n', v: '' },
  H10: { t: 'n', v: '' },
  I10: { t: 'n', v: 0, w: '0' },
  J10: { t: 'n', v: 0, w: '0' },
  K10: { t: 'n', v: 0, w: '0' },
  L10: { t: 'n', v: 0, w: '0' },
  M10: { t: 'n', v: 0, w: '0' },
  N10: { t: 'n', v: 0, w: '0' },
  O10: { t: 'n', v: 0, w: '0' },
  P10: { t: 'n', v: 0, w: '0' },
  Q10: { t: 'n', v: 0, w: '0' },
  R10: { t: 'n', v: '' },
  S10: { t: 'n', v: '' },
  A11: {
    t: 's',
    v: '备注：保洁工作时间：7：30-17：00，共8个小时',
    r: '<t>å¤æ³¨ï¼ä¿å·¥ä½æ¶é´ï¼7ï¼30-17ï¼00ï¼å±8ä¸ªå°æ¶</t>',
    h: '备注：保洁工作时间：7：30-17：00，共8个小时',
    w: '备注：保洁工作时间：7：30-17：00，共8个小时',
  },
  B11: { t: 'n', v: '' },
  C11: { t: 'n', v: '' },
  D11: { t: 'n', v: '' },
  E11: { t: 'n', v: '' },
  F11: { t: 'n', v: '' },
  G11: { t: 'n', v: '' },
  H11: { t: 'n', v: '' },
  I11: { t: 'n', v: '' },
  J11: { t: 'n', v: '' },
  K11: { t: 'n', v: '' },
  L11: { t: 'n', v: '' },
  M11: { t: 'n', v: '' },
  N11: { t: 'n', v: '' },
  O11: { t: 'n', v: '' },
  P11: { t: 'n', v: '' },
  Q11: { t: 'n', v: '' },
  R11: { t: 'n', v: '' },
  S11: { t: 'n', v: '' },
  '!merges': [
    { s: { c: 1, r: 8 }, e: { c: 7, r: 8 } },
    { s: { c: 1, r: 9 }, e: { c: 7, r: 9 } },
    { s: { c: 0, r: 10 }, e: { c: 18, r: 10 } },
    { s: { c: 0, r: 0 }, e: { c: 0, r: 1 } },
    { s: { c: 0, r: 2 }, e: { c: 0, r: 4 } },
    { s: { c: 0, r: 5 }, e: { c: 0, r: 7 } },
    { s: { c: 1, r: 0 }, e: { c: 1, r: 1 } },
    { s: { c: 1, r: 2 }, e: { c: 1, r: 4 } },
    { s: { c: 1, r: 5 }, e: { c: 1, r: 7 } },
    { s: { c: 2, r: 0 }, e: { c: 2, r: 1 } },
    { s: { c: 2, r: 2 }, e: { c: 2, r: 4 } },
    { s: { c: 2, r: 5 }, e: { c: 2, r: 7 } },
    { s: { c: 3, r: 0 }, e: { c: 3, r: 1 } },
    { s: { c: 3, r: 2 }, e: { c: 3, r: 4 } },
    { s: { c: 3, r: 5 }, e: { c: 3, r: 7 } },
    { s: { c: 4, r: 0 }, e: { c: 4, r: 1 } },
    { s: { c: 4, r: 2 }, e: { c: 4, r: 4 } },
    { s: { c: 4, r: 5 }, e: { c: 4, r: 7 } },
    { s: { c: 5, r: 0 }, e: { c: 5, r: 1 } },
    { s: { c: 5, r: 2 }, e: { c: 5, r: 4 } },
    { s: { c: 5, r: 5 }, e: { c: 5, r: 7 } },
    { s: { c: 6, r: 0 }, e: { c: 6, r: 1 } },
    { s: { c: 6, r: 2 }, e: { c: 6, r: 4 } },
    { s: { c: 6, r: 5 }, e: { c: 6, r: 7 } },
    { s: { c: 7, r: 0 }, e: { c: 7, r: 1 } },
    { s: { c: 16, r: 0 }, e: { c: 16, r: 1 } },
    { s: { c: 16, r: 2 }, e: { c: 16, r: 4 } },
    { s: { c: 16, r: 5 }, e: { c: 16, r: 7 } },
    { s: { c: 17, r: 0 }, e: { c: 17, r: 1 } },
    { s: { c: 17, r: 2 }, e: { c: 17, r: 4 } },
    { s: { c: 17, r: 5 }, e: { c: 17, r: 7 } },
    { s: { c: 18, r: 0 }, e: { c: 18, r: 1 } },
    { s: { c: 18, r: 2 }, e: { c: 18, r: 4 } },
    { s: { c: 18, r: 5 }, e: { c: 18, r: 7 } },
  ],
};
let s = [
  { patternType: 'none' },
  { patternType: 'gray125' },
  { patternType: 'solid', fgColor: { theme: 0, tint: -0.15 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 4, tint: 0.599993896298105 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 7, tint: 0.399975585192419 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 6, tint: 0.799981688894314 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 4 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { rgb: 'FFC6EFCE' }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { rgb: 'FFF2F2F2' }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { rgb: 'FFFFC7CE' }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 7 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { rgb: 'FFA5A5A5' }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 4, tint: 0.399975585192419 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 6, tint: 0.599993896298105 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 8, tint: 0.399975585192419 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 5, tint: 0.599993896298105 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 5, tint: 0.399975585192419 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { rgb: 'FFFFFFCC' }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { rgb: 'FFFFCC99' }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 8, tint: 0.599993896298105 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 7, tint: 0.599993896298105 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { rgb: 'FFFFEB9C' }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 6 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 5, tint: 0.799981688894314 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 6, tint: 0.399975585192419 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 8 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 7, tint: 0.799981688894314 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 4, tint: 0.799981688894314 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 8, tint: 0.799981688894314 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 5 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 9, tint: 0.799981688894314 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 9 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 9, tint: 0.599993896298105 }, bgColor: { indexed: 64 } },
  { patternType: 'solid', fgColor: { theme: 9, tint: 0.399975585192419 }, bgColor: { indexed: 64 } },
];
let xml = [
  {
    name: '考勤记录_1',
    data: [
      ['考勤记录'],
      ['部门编号', '部门名称', '人员编号', '姓名', '时间', '验证方式', '设备名称'],
      [
        '000121.18.05.05.01',
        '合肥壹号院案场',
        '9940046',
        '李有芬',
        '2020-03-01 07:17:06',
        '人脸',
        'ACY8184160233(物业-东南-安徽-合肥壹号院案场)',
      ],
    ],
  },
];
b = [
  {},
  {
    left: { style: 'thin', color: { auto: '1' } },
    right: { style: 'thin', color: { auto: '1' } },
    top: { style: 'thin', color: { auto: '1' } },
    bottom: { style: 'thin', color: { auto: '1' } },
  },
  {
    left: { style: 'thin', color: { rgb: 'FF3F3F3F' } },
    right: { style: 'thin', color: { rgb: 'FF3F3F3F' } },
    top: { style: 'thin', color: { rgb: 'FF3F3F3F' } },
    bottom: { style: 'thin', color: { rgb: 'FF3F3F3F' } },
  },
  {
    left: { style: 'double', color: { rgb: 'FF3F3F3F' } },
    right: { style: 'double', color: { rgb: 'FF3F3F3F' } },
    top: { style: 'double', color: { rgb: 'FF3F3F3F' } },
    bottom: { style: 'double', color: { rgb: 'FF3F3F3F' } },
  },
  {
    left: { style: 'thin', color: { rgb: 'FFB2B2B2' } },
    right: { style: 'thin', color: { rgb: 'FFB2B2B2' } },
    top: { style: 'thin', color: { rgb: 'FFB2B2B2' } },
    bottom: { style: 'thin', color: { rgb: 'FFB2B2B2' } },
  },
  {
    left: { style: 'thin', color: { rgb: 'FF7F7F7F' } },
    right: { style: 'thin', color: { rgb: 'FF7F7F7F' } },
    top: { style: 'thin', color: { rgb: 'FF7F7F7F' } },
    bottom: { style: 'thin', color: { rgb: 'FF7F7F7F' } },
  },
  { bottom: { style: 'double', color: { rgb: 'FFFF8001' } } },
  { bottom: { style: 'medium', color: { theme: '4' } } },
  { top: { style: 'thin', color: { theme: '4' } }, bottom: { style: 'double', color: { theme: '4' } } },
  { bottom: { style: 'medium', color: { theme: '4', tint: '0.499984740745262' } } },
];
